# Root a folder for data
artifact_root: artifacts

# Create directory to ingest data  
data_ingestion:
  root_dir: artifacts/ data_ingestion
  source_url: https://github.com/tina96pham/project_dataset/raw/main/endtoend_MLtemplate.zip
  local_data_file: artifacts/data/endtoend_MLtemplate_data.zip
  unzip_dir: artifacts/data_ingestion